--CREATE TABLE DV_NEW_RECORDS_ (
--CAT varchar(20),
--SUBCAT varchar(20),
--BOREHOLE_NAME varchar(20),
--BLOCK_NAME varchar(10),
--CREATED_DATE date
--);
--REM INSERTING into DV_NEW_RECORDS_; 
--SET DEFINE OFF;
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','AABBCC','BS','29-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','B-157N-9','MUM','28-APR-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','B-211-2','MUM','26-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','WO-5-17','MH','25-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','D-1-24','BS','24-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','WO24-3-6','MH','24-APR-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','D1-E-4','MUM','23-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','BSE-16','MUM','17-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','N10-3ZH','MH','16-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','B-127N-4','MUM','15-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','HE-7XH','NH','12-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','R-12-11','NH','12-APR-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','BF-9ZH','BS','11-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','BE-7XH','BS','11-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','BSE-15','MUM','11-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','B173A-C-2Z','NH','10-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','B-157C-2','MUM','09-MAY-2023');
--Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','WELL_CREATION','ND-2ZH','MH','04-APR-2023');

--Select * from DV_NEW_RECORDS_;
--
--drop table DV_NEW_RECORDS_;


REM INSERTING into DV_NEW_RECORDS_
SET DEFINE OFF;
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','CONV_CORE','B-157N-8','MUM','31-JAN-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','CONV_CORE','BH-88','MH','28-FEB-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','CONV_CORE','BH-86','MH','28-FEB-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','CONV_CORE','B-57N-3','MUM','21-JAN-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','CONV_CORE','C-37-8','MUM','14-DEC-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','CONV_CORE','R-12-10','NH','13-OCT-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','CONV_CORE','B-12-32','BS','10-NOV-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','CONV_CORE','MBS171HAA-1','MUM','10-JAN-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','CONV_CORE','BH-85','MH','02-DEC-2022');

REM INSERTING into DV_NEW_RECORDS_
SET DEFINE OFF;
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','WO-24-3','MUM','30-MAR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','BH-88','MH','28-FEB-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','HR-B','NH','22-FEB-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','B-57N-3','MUM','21-JAN-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','VGS-2','MUM','20-FEB-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','B-154N-5','MUM','17-FEB-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','B-12-31','BS','14-OCT-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','WO-16-14','MH','14-OCT-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','R-12-10','NH','13-OCT-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','B-12-34','BS','13-OCT-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','BH-87','MH','13-OCT-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','B-157N-7','MUM','12-OCT-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','WO-5-16','MH','12-DEC-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','B-192-21','MH','11-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','B-12-32','BS','10-NOV-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','MBS171HAA-1','MUM','10-JAN-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','B-45-7','MUM','06-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('GEOLOGY','SWC','BH-86','MH','01-MAR-2023');

REM INSERTING into DV_NEW_RECORDS_
SET DEFINE OFF;
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','N1-2Y','MH','27-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','S1-6-11Z','MH','27-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','MBS182HDA-1','MUM','27-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','MBS182HAA-1','MUM','26-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','WO24-3-6','MH','26-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','B-12-34','BS','25-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','D-33-9','MUM','21-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','MBS181HCA-1','MUM','20-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','HE-7XH','NH','18-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','BE-7XH','BS','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','B173A-C-2Z','NH','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','BF-9ZH','BS','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','NTP-2-1H','BS','12-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','NTP-1-2H','BS','12-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','ND-2ZH','MH','11-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','B-53-2','MUM','11-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','SY-9Z','MH','10-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','SD-16','MUM','10-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','N-4-1Z','MH','10-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','MBS181HBA-1','MUM','06-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','VSEA-6ZH','BS','04-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','COMPOSITE_LOGS','B-157-P1','MH','02-MAY-2023');

REM INSERTING into DV_NEW_RECORDS_
SET DEFINE OFF;
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS181HBA-1','MUM','29-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-157-P1','MH','28-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','SD-3Z','MH','27-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-57N-4','MUM','27-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-53-2','MUM','27-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','SV-6Z','MH','27-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS181HCA-1','MUM','27-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-55-8','BS','27-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','SD-16','MUM','27-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS181HBA-1','MUM','27-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','SD-3Z','MH','24-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','N6-9Z','MH','23-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','D1-E-4','MUM','23-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','N6-7Z','MH','23-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-157N-9','MUM','23-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-157C-2','MUM','23-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NLM-6-7XH','NH','23-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','HE-7XH','NH','23-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-157N-9','MUM','22-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NLM-6-2YH','NH','22-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS182HDA-1','MUM','22-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NLM-8-3XH','NH','19-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS182HDA-1','MUM','19-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NTP-2-4H','BS','19-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NLM-11-1XH','NH','19-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-172-7','MUM','18-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NLM-4-10ZH','NH','18-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-173A-B2H','NH','18-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NLM-4-3YH','NH','18-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NLM-3-11YH','NH','18-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-157N-9','MUM','18-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS182HAA-1','MUM','18-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-173A-B-3ZH','NH','17-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','N10-3ZH','MH','17-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NLM-6-2XH','NH','17-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','SD-3Z','MH','17-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS182HAA-1','MUM','17-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','HI-9','NH','16-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','R-12-11','NH','16-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-157N-9','MUM','16-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS182HDA-1','MUM','16-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','HE-7XH','NH','16-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-157C-2','MUM','16-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-173A-B2H','NH','16-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','SF-7Z','MH','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','BF-9ZH','BS','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','N19-6H','MH','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','SD-16','MUM','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','ST-6','MUM','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','WO24-3-6','MH','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS181HBA-1','MUM','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS181HCA-1','MUM','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-53-2','MUM','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','ND-2ZH','MH','15-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NTP-1-2H','BS','12-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','BF-9ZH','BS','12-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','HE-7XH','NH','12-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NTP-2-1H','BS','12-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','WO24-3-6','MH','12-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','D-33-9','MUM','12-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','HY-2ZH','NH','11-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B173A-C-2Z','NH','11-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS182HAA-1','MUM','11-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','BE-7XH','BS','11-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','N-4-1Z','MH','11-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','WO24-3-6','MH','11-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','SY-9Z','MH','10-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-55-8','BS','10-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS181HCA-1','MUM','09-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS181HBA-1','MUM','09-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-173A-A6YH','NH','09-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-157C-2','MUM','09-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','SB-18','MUM','09-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-173A-A3YH','NH','08-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','RS5-5H-ML1','MH','08-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','RS5-3H-ML1','MH','08-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','HY-2ZH','NH','05-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','ND-2ZH','MH','05-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','WB-15H-ML1','MH','04-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','RS5-1H-ML1','MH','04-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','WA-10H-ML1','MH','04-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','BH-4H','BS','04-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NLM-6-2XH','NH','04-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','BS-13A-2ZH','BS','04-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','SV-6Z','MH','04-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','HY-7W','NH','04-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','MBS181HCA-1','MUM','04-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-55-8','BS','04-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','BE-7YH','BS','04-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','SD-3Z','MH','04-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B192-5A-6','MH','04-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','B-173A-A6YH','NH','03-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','VSEA-6ZH','BS','03-APR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','NLM-3-8YH','NH','02-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','PG-1','BS','02-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','BE-7Z','BS','02-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','IF-11ZH','MH','02-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','SD-16','MUM','01-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','HY-2ZH','NH','01-MAY-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LOGGING','ORIGINAL_LOGS','N1-6H','MH','01-MAY-2023');

REM INSERTING into DV_NEW_RECORDS_
SET DEFINE OFF;
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','C-37-8','MUM','30-JAN-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','B-157N-8','MUM','30-JAN-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','MBS171HAA-1','MUM','30-JAN-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','B-149-7','MUM','29-NOV-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','B-55-7','BS','29-NOV-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','CGS-1-1','MUM','29-NOV-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','WO-5-15','MH','29-NOV-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','WO-24-8','MUM','29-JUN-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','B-12-28','MUM','29-JUN-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','WO-24-5','MUM','29-JUN-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','MBS051NAA-4','MUM','29-JUN-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','B-57N-3','MUM','27-MAR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','C-37-8','MUM','27-MAR-2023');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','WO-5-16','MH','27-DEC-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','BH-86','MH','27-DEC-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','MBS171HAA-1','MUM','27-DEC-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','B-157N-7','MUM','26-JUL-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','MB-10','BS','26-JUL-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','B-154N-5','MUM','26-JUL-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','B-12-33','BS','26-JUL-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','C-37-7','MUM','26-JUL-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','B-12-28','MUM','25-MAY-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','WO-24-5','MUM','25-MAY-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','WO-15-6','MUM','25-APR-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','B-41-2','MUM','25-APR-2022');
Insert into DV_NEW_RECORDS_ (CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE) values ('LAB_DATA','WATER_LAB','B-219-1','MUM','25-APR-2022');


SELECT * FROM DV_NEW_RECORDS_ WHERE CAT='GEOLOGY';

CREATE VIEW DV_NEW_RECORDS AS SELECT CAT,SUBCAT,BOREHOLE_NAME,BLOCK_NAME,CREATED_DATE FROM DV_NEW_RECORDS_ ORDER BY PRIORITY;
DROP VIEW DV_NEW_RECORDS;
ALTER table DV_NEW_RECORDS_ ADD PRIORITY INT;

UPDATE DV_NEW_RECORDS_
SET PRIORITY = 1
WHERE CAT = 'GEOLOGY' AND SUBCAT = 'WELL_CREATION';
UPDATE DV_NEW_RECORDS_
SET PRIORITY = 2
WHERE CAT = 'GEOLOGY' AND SUBCAT = 'CONV_CORE';
UPDATE DV_NEW_RECORDS_
SET PRIORITY = 3
WHERE CAT = 'GEOLOGY' AND SUBCAT = 'SWC';
UPDATE DV_NEW_RECORDS_
SET PRIORITY = 4
WHERE CAT = 'LOGGING' AND SUBCAT = 'ORIGINAL_LOGS';
UPDATE DV_NEW_RECORDS_
SET PRIORITY = 5
WHERE CAT = 'LOGGING' AND SUBCAT = 'COMPOSITE_LOGS';
UPDATE DV_NEW_RECORDS_
SET PRIORITY = 6
WHERE CAT = 'LAB_DATA' AND SUBCAT = 'WATER_LAB';


